# Generated by Django 4.2.9 on 2024-02-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="dbportfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=100, unique=True, verbose_name="Clave"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("url", models.URLField(blank=True, null=True, verbose_name="Enlace")),
                ("image", models.ImageField(upload_to="static/img")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha creación"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "PortFolios",
                "ordering": ["name"],
            },
        ),
    ]
