# Generated by Django 4.2.9 on 2024-02-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbportfolio",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creación"),
        ),
        migrations.AlterField(
            model_name="dbportfolio",
            name="image",
            field=models.ImageField(upload_to="static/img", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="dbportfolio",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Actualización"),
        ),
    ]
