# Generated by Django 4.2.9 on 2024-02-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folio", "0002_alter_dbportfolio_created_alter_dbportfolio_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dbportfolio",
            name="created",
        ),
        migrations.RemoveField(
            model_name="dbportfolio",
            name="image",
        ),
        migrations.RemoveField(
            model_name="dbportfolio",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="dbportfolio",
            name="url",
        ),
        migrations.AlterField(
            model_name="dbportfolio",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Name"),
        ),
    ]
