# Generated by Django 4.2.9 on 2024-02-01 02:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("folio", "0003_remove_dbportfolio_created_remove_dbportfolio_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="dbportfolio",
        ),
    ]
