# Generated by Django 4.2.9 on 2024-02-01 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("folio", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbportfolio",
            name="image",
            field=models.ImageField(upload_to="folio/static/img", verbose_name="Image"),
        ),
    ]
